class StatusInscricao:
    INSCRITO = "INSCRITO"
    VALIDADO_SECRETARIA = "VALIDADO_SECRETARIA"
    REJEITADO_SECRETARIA = "REJEITADO_SECRETARIA"
    SELECIONADO_ORIENTADOR = "SELECIONADO_ORIENTADOR"
    CADASTRADO_FINAL = "CADASTRADO_FINAL"
